In [1]:
#import libraries
import pandas as pd
import numpy as np
import numpy.random as npr

#import models from scikit learn module:
#for data splitting
from sklearn.model_selection import train_test_split
#for data standardization
from sklearn.preprocessing import StandardScaler
#for Naive Bayes
from sklearn.naive_bayes import BernoulliNB
#for K-Nearest Neighbors (KNN)
from sklearn.neighbors import KNeighborsClassifier
#for Support Vector Machine (SVM)
from sklearn import svm
#for evaluation of accuracy
from sklearn import metrics
from sklearn.metrics import precision_score, recall_score, confusion_matrix, classification_report, accuracy_score, f1_score

In [2]:
cd C:/Users/CHONG WEN QIN/Downloads

C:\Users\CHONG WEN QIN\Downloads


In [3]:
# Reading the dataset in a dataframe using Pandas
df = pd.read_csv("heart_disease.csv")
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [4]:
#Get summary of numerical variables
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [5]:
# Reading the features of dataset
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [6]:
# Check the data types of each features
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [7]:
# Check if there is null in the dataset
df.apply(lambda x: sum(x.isnull()), axis = 0)

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [8]:
# Check if there is duplicate in the dataset
df.duplicated().sum()

1

In [9]:
# Drop the duplicates
df.drop_duplicates(inplace = True)
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[302 rows x 14 columns]

In [10]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  302.00000  302.000000  302.000000  302.000000  302.000000  302.000000   
mean    54.42053    0.682119    0.963576  131.602649  246.500000    0.149007   
std      9.04797    0.466426    1.032044   17.563394   51.753489    0.356686   
min     29.00000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     48.00000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.50000    1.000000    1.000000  130.000000  240.500000    0.000000   
75%     61.00000    1.000000    2.000000  140.000000  274.750000    0.000000   
max     77.00000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  302.000000  302.000000  302.000000  302.000000  302.000000  302.000000   
mean     0.526490  149.569536    0.327815    1.043046    1.397351    0.718543   
std      0.526027   22.903527    0.470196    1.161452    0.616274    1.006748   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.250000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  152.500000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  302.000000  302.000000  
mean     2.314570    0.543046  
std      0.613026    0.498970  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [11]:
df['target'].value_counts()

target
1    164
0    138
Name: count, dtype: int64

In [12]:
X = df[['cp','trestbps','chol','fbs','restecg']]
Y = df['target']

In [13]:
# Splitting data into 60% train set and 40% test set
X_train60,X_test40,Y_train60,Y_test40 = train_test_split(X,Y,random_state = 0,test_size = 0.4)
# Splitting data into 70% train set and 30% test set
X_train70,X_test30,Y_train70,Y_test30 = train_test_split(X,Y,random_state = 0,test_size = 0.3)
# Splitting data into 80% train set and 20% test set
X_train80,X_test20,Y_train80,Y_test20 = train_test_split(X,Y,random_state = 0,test_size = 0.2)

In [14]:
# Data Standardization
sd = StandardScaler()
X_train60 = sd.fit_transform(X_train60)
X_test40 = sd.transform(X_test40)
X_train70 = sd.fit_transform(X_train70)
X_test30 = sd.transform(X_test30)
X_train80 = sd.fit_transform(X_train80)
X_test20 = sd.transform(X_test20)

In [15]:
print(X_train60.shape)
print(X_test40.shape)
print(X_train70.shape)
print(X_test30.shape)
print(X_train80.shape)
print(X_test20.shape)

(181, 5)
(121, 5)
(211, 5)
(91, 5)
(241, 5)
(61, 5)


In [16]:
print(Y_train60.shape)
print(Y_test40.shape)
print(Y_train70.shape)
print(Y_test30.shape)
print(Y_train80.shape)
print(Y_test20.shape)

(181,)
(121,)
(211,)
(91,)
(241,)
(61,)


In [17]:
# Fit the data into Naive Bayes Model
NB_model60 = BernoulliNB()
NB_model70 = BernoulliNB()
NB_model80 = BernoulliNB()

NB_model60.fit(X_train60,Y_train60)
NB_model70.fit(X_train70,Y_train70)
NB_model80.fit(X_train80,Y_train80)

BernoulliNB()

In [18]:
# Predict the test set results
NB_pred40=NB_model60.predict(X_test40)
NB_pred30=NB_model70.predict(X_test30)
NB_pred20=NB_model80.predict(X_test20)

In [19]:
# Evaluate the accuracy
print("60% Train and 40% Test")
print('Accuracy:', accuracy_score(Y_test40, NB_pred40))
print('Recall', recall_score(Y_test40, NB_pred40, average = "weighted"))
print ('Precision:', precision_score(Y_test40, NB_pred40, average="weighted"))
print ('F1 score:', f1_score(Y_test40, NB_pred40, average = "weighted"))
NB_confusion40 = confusion_matrix(Y_test40, NB_pred40)
print('Confusion matrix:')
print(NB_confusion40)

print("\n70% Train and 30% Test")
print('Accuracy:', accuracy_score(Y_test30, NB_pred30))
print('Recall', recall_score(Y_test30, NB_pred30, average = "weighted"))
print ('Precision:', precision_score(Y_test30, NB_pred30, average = "weighted"))
print ('F1 score:', f1_score(Y_test30, NB_pred30, average = "weighted"))
NB_confusion30 = confusion_matrix(Y_test30, NB_pred30)
print('Confusion matrix:')
print(NB_confusion30)

print("\n80% Train and 20% Test")
print('Accuracy:', accuracy_score(Y_test20, NB_pred20))
print('Recall', recall_score(Y_test20, NB_pred20, average = "weighted"))
print ('Precision:', precision_score(Y_test20, NB_pred20, average = "weighted"))
print ('F1 score:', f1_score(Y_test20, NB_pred20, average = "weighted"))
NB_confusion20 = confusion_matrix(Y_test20, NB_pred20)
print('Confusion matrix:')
print(NB_confusion20)

60% Train and 40% Test
Accuracy: 0.7851239669421488
Recall 0.7851239669421488
Precision: 0.7853772838098857
F1 score: 0.7850358548454875
Confusion matrix:
[[46 14]
 [12 49]]

70% Train and 30% Test
Accuracy: 0.7912087912087912
Recall 0.7912087912087912
Precision: 0.7912991264055095
F1 score: 0.7911583402703374
Confusion matrix:
[[35 10]
 [ 9 37]]

80% Train and 20% Test
Accuracy: 0.8032786885245902
Recall 0.8032786885245902
Precision: 0.8032786885245902
F1 score: 0.8032786885245902
Confusion matrix:
[[21  6]
 [ 6 28]]


In [20]:
# Check for overfit
NB_trainpred60 = NB_model60.predict(X_train60)
NB_trainpred70 = NB_model70.predict(X_train70)
NB_trainpred80 = NB_model80.predict(X_train80)

print("Overfitting Checking for Naive Bayes")
print("\n60% Train and 40% Test")
print('Accuracy for test set :', accuracy_score(Y_test40, NB_pred40))
print('Accuracy for train set :', accuracy_score(Y_train60, NB_trainpred60))

print("\n70% Train and 30% Test")
print('Accuracy for test set :', accuracy_score(Y_test30, NB_pred30))
print('Accuracy for train set :', accuracy_score(Y_train70, NB_trainpred70))

print("\n80% Train and 20% Test")
print('Accuracy for test set :', accuracy_score(Y_test20, NB_pred20))
print('Accuracy for train set :', accuracy_score(Y_train80, NB_trainpred80))

Overfitting Checking for Naive Bayes

60% Train and 40% Test
Accuracy for test set : 0.7851239669421488
Accuracy for train set : 0.7403314917127072

70% Train and 30% Test
Accuracy for test set : 0.7912087912087912
Accuracy for train set : 0.7440758293838863

80% Train and 20% Test
Accuracy for test set : 0.8032786885245902
Accuracy for train set : 0.7468879668049793


In [21]:
# Find the best k-value
splits = [(X_train60,X_test40,Y_train60,Y_test40),(X_train70,X_test30,Y_train70,Y_test30),(X_train80,X_test20,Y_train80,Y_test20)]
k_values = range(1,30) 
avg_accuracy_per_k = []

for k in k_values:
    accuracies = []

    for X_train, X_test, Y_train, Y_test in splits:
        knn = KNeighborsClassifier(n_neighbors=k)
        knn.fit(X_train, Y_train)

        Y_pred = knn.predict(X_test)
        
        accuracy = np.mean(Y_pred == Y_test)
        accuracies.append(accuracy)

    avg_accuracy = np.mean(accuracies)
    avg_accuracy_per_k.append((k, avg_accuracy))

best_k, best_avg_accuracy = max(avg_accuracy_per_k, key=lambda x: x[1])

print('Best k value:', best_k, 'with average accuracy:', best_avg_accuracy)

Best k value: 18 with average accuracy: 0.7712555700633197


In [22]:
# Fit the train set into the model using k = 18
knn_model60 = KNeighborsClassifier(n_neighbors = 18)
knn_model70 = KNeighborsClassifier(n_neighbors = 18)
knn_model80 = KNeighborsClassifier(n_neighbors = 18)

knn_model60.fit(X_train60, Y_train60)
knn_model70.fit(X_train70, Y_train70)
knn_model80.fit(X_train80, Y_train80)

KNeighborsClassifier(n_neighbors=18)

In [23]:
# Predict the test set results
knn_pred40 = knn_model60.predict(X_test40)
knn_pred30 = knn_model70.predict(X_test30)
knn_pred20 = knn_model80.predict(X_test20)

In [24]:
# Evaluate the accuracy
print("60% Train and 40% Test")
print('Accuracy:', accuracy_score(Y_test40, knn_pred40))
print('Recall:', recall_score(Y_test40, knn_pred40, average = "weighted"))
print('Precision:', precision_score(Y_test40, knn_pred40, average = "weighted"))
print ('F1 score:', f1_score(Y_test40, knn_pred40, average = "weighted"))
knn_confusion40 = confusion_matrix(Y_test40, knn_pred40)
print('Confusion matrix:')
print(knn_confusion40)

print("\n70% Train and 30% Test")
print('Accuracy:', accuracy_score(Y_test30, knn_pred30))
print('Recall:', recall_score(Y_test30, knn_pred30, average = "weighted"))
print('Precision:', precision_score(Y_test30, knn_pred30, average = "weighted"))
print ('F1 score:', f1_score(Y_test30, knn_pred30, average = "weighted"))
knn_confusion30 = confusion_matrix(Y_test30, knn_pred30)
print('Confusion matrix:')
print(knn_confusion30)

print("\n80% Train and 20% Test")
print('Accuracy:', accuracy_score(Y_test20, knn_pred20))
print('Recall:', recall_score(Y_test20, knn_pred20, average = "weighted"))
print('Precision:', precision_score(Y_test20, knn_pred20, average = "weighted"))
print ('F1 score:', f1_score(Y_test20, knn_pred20, average = "weighted"))
knn_confusion20 = confusion_matrix(Y_test20, knn_pred20)
print('Confusion matrix:')
print(knn_confusion20)

60% Train and 40% Test
Accuracy: 0.7520661157024794
Recall: 0.7520661157024794
Precision: 0.752409526951005
F1 score: 0.7520322449532584
Confusion matrix:
[[46 14]
 [16 45]]

70% Train and 30% Test
Accuracy: 0.7912087912087912
Recall: 0.7912087912087912
Precision: 0.7923301188607311
F1 score: 0.7909056460780599
Confusion matrix:
[[34 11]
 [ 8 38]]

80% Train and 20% Test
Accuracy: 0.7704918032786885
Recall: 0.7704918032786885
Precision: 0.7733889202939513
F1 score: 0.7711127670144063
Confusion matrix:
[[21  6]
 [ 8 26]]


In [25]:
# Check for overfit
knn_trainpred60 = knn_model60.predict(X_train60)
knn_trainpred70 = knn_model70.predict(X_train70)
knn_trainpred80 = knn_model80.predict(X_train80)

print("Overfitting Checking for K-Nearest Neighbors")
print("60% Train and 40% Test")
print('Accuracy for test set :', accuracy_score(Y_test40, knn_pred40))
print('Accuracy for train set :', accuracy_score(Y_train60, knn_trainpred60))

print("\n70% Train and 30% Test")
print('Accuracy for test set :', accuracy_score(Y_test30, knn_pred30))
print('Accuracy for train set :', accuracy_score(Y_train70, knn_trainpred70))

print("\n80% Train and 20% Test")
print('Accuracy for test set :', accuracy_score(Y_test20, knn_pred20))
print('Accuracy for train set :', accuracy_score(Y_train80, knn_trainpred80))

Overfitting Checking for K-Nearest Neighbors
60% Train and 40% Test
Accuracy for test set : 0.7520661157024794
Accuracy for train set : 0.7348066298342542

70% Train and 30% Test
Accuracy for test set : 0.7912087912087912
Accuracy for train set : 0.7440758293838863

80% Train and 20% Test
Accuracy for test set : 0.7704918032786885
Accuracy for train set : 0.7510373443983402


In [26]:
# Fit the data into SVM Model
SVM_model60 = svm.SVC()
SVM_model70 = svm.SVC()
SVM_model80 = svm.SVC()

SVM_model60.fit(X_train60,Y_train60)
SVM_model70.fit(X_train70,Y_train70)
SVM_model80.fit(X_train80,Y_train80)

SVC()

In [27]:
# Predict the test set results
SVM_pred40 = SVM_model60.predict(X_test40)
SVM_pred30 = SVM_model70.predict(X_test30)
SVM_pred20 = SVM_model80.predict(X_test20)

In [28]:
# Evaluate the accuracy
print("60% Train and 40% Test")
print('Accuracy:', accuracy_score(Y_test40, SVM_pred40))
print('Recall:', recall_score(Y_test40, SVM_pred40, average = "weighted"))
print('Precision:', precision_score(Y_test40, SVM_pred40, average = "weighted"))
print ('F1 score:', f1_score(Y_test40, SVM_pred40, average = "weighted"))
SVM_confusion40 = confusion_matrix(Y_test40, SVM_pred40)
print('Confusion matrix:')
print(SVM_confusion40)

print("\n70% Train and 30% Test")
print('Accuracy:', accuracy_score(Y_test30, SVM_pred30))
print('Recall:', recall_score(Y_test30, SVM_pred30, average = "weighted"))
print('Precision:', precision_score(Y_test30, SVM_pred30, average = "weighted"))
print ('F1 score:', f1_score(Y_test30, SVM_pred30, average = "weighted"))
SVM_confusion30 = confusion_matrix(Y_test30, SVM_pred30)
print('Confusion matrix:')
print(SVM_confusion30)

print("\n80% Train and 20% Test")
print('Accuracy:', accuracy_score(Y_test20, SVM_pred20))
print('Recall:', recall_score(Y_test20, SVM_pred20, average = "weighted"))
print('Precision:', precision_score(Y_test20, SVM_pred20, average = "weighted"))
print ('F1 score:', f1_score(Y_test20, SVM_pred20, average = "weighted"))
SVM_confusion20 = confusion_matrix(Y_test20, SVM_pred20)
print('Confusion matrix:')
print(SVM_confusion20)

60% Train and 40% Test
Accuracy: 0.7603305785123967
Recall: 0.7603305785123967
Precision: 0.7636372808908376
F1 score: 0.7594098480738081
Confusion matrix:
[[42 18]
 [11 50]]

70% Train and 30% Test
Accuracy: 0.7912087912087912
Recall: 0.7912087912087912
Precision: 0.7912991264055095
F1 score: 0.7911583402703374
Confusion matrix:
[[35 10]
 [ 9 37]]

80% Train and 20% Test
Accuracy: 0.8032786885245902
Recall: 0.8032786885245902
Precision: 0.8032786885245902
F1 score: 0.8032786885245902
Confusion matrix:
[[21  6]
 [ 6 28]]


In [29]:
# Check for overfit
SVM_trainpred60 = SVM_model60.predict(X_train60)
SVM_trainpred70 = SVM_model70.predict(X_train70)
SVM_trainpred80 = SVM_model80.predict(X_train80)

print("Overfitting Checking for Support Vector Machine")
print("60% Train and 40% Test")
print('Accuracy for test set :', accuracy_score(Y_test40, SVM_pred40))
print('Accuracy for train set :', accuracy_score(Y_train60, SVM_trainpred60))

print("\n70% Train and 30% Test")
print('Accuracy for test set :', accuracy_score(Y_test30, SVM_pred30))
print('Accuracy for train set :', accuracy_score(Y_train70, SVM_trainpred70))

print("\n80% Train and 20% Test")
print('Accuracy for test set :', accuracy_score(Y_test20, SVM_pred20))
print('Accuracy for train set :', accuracy_score(Y_train80, SVM_trainpred80))

Overfitting Checking for Support Vector Machine
60% Train and 40% Test
Accuracy for test set : 0.7603305785123967
Accuracy for train set : 0.7790055248618785

70% Train and 30% Test
Accuracy for test set : 0.7912087912087912
Accuracy for train set : 0.7582938388625592

80% Train and 20% Test
Accuracy for test set : 0.8032786885245902
Accuracy for train set : 0.7634854771784232
